spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_schema: jwtapplication
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    password: ${DATABASE_PASSWORD}
    username: ${DATABASE_USER}
    hikari:
      connection-timeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
